name: Test

on:
  push:
    branches:
      - main
    paths: &test-paths
      - "**.ts"
      - ".github/workflows/test.yml"
      - "deno.json"
      - "deno.lock"
  pull_request:
    paths: *test-paths

jobs:
  lint:
    runs-on: &target-os ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with: &deno-config
          deno-version: v2.x
          cache: true

      - name: Run Lint
        run: deno lint

  test:
    runs-on: *target-os
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with: *deno-config

      - name: Run Tests
        run: deno task test
